#!/usr/bin/env perl 
#===============================================================================
#
#  DESCRIPTION: 
#
#      CREATED: 31.12.2018 21:07:08
#===============================================================================

use strict;
use warnings;

use 5.014;
use Data::Dumper;

use FindBin;
use File::Spec;

say "\$Bin:    $FindBin::Bin";
say "\$Script: $FindBin::Script";
say '';
say "\$RealBin:    $FindBin::RealBin";
say "\$RealScript: $FindBin::RealScript";
say '';
say "user's home dir: $ENV{HOME}";
