#!/usr/bin/env perl 
#===============================================================================
#
#  DESCRIPTION: 
#
#      CREATED: 31.12.2018 21:07:08
#===============================================================================

use strict;
use warnings;

use 5.014;
use Data::Dumper;

use FindBin;
use File::Spec;

# check for windows
my $isWin;
$isWin = 1 if exists $ENV{OS} and $ENV{OS} eq 'Windows_NT';

my $home = ($isWin ? $ENV{USERPROFILE} : $ENV{HOME});

# be safe
$home = doSafePath($home);
say $home;

# be safe again
my $distrHome = doSafePath($FindBin::Bin);
say $distrHome;

if ($isWin) {
    ...
}
else {
}

#say "\$Bin:    $FindBin::Bin";
## $Bin:    /home/xxxxx/glowing-broccoli
#say '';
#say "user's home dir: $ENV{HOME}";
## user's home dir: /home/xxxxx
##
## on windows:
##  - git bash
##  user's home dir: /c/Users/XXXXX
##  - power shell, cmd
##  Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at install line 24.
##  user's home dir:
##
## on windows, the $ENV{USERPROFILE} is better:
##  - power shell, cmd
##  $VAR1 = \'C:\\Users\\XXXXX';

sub doSafePath {
    my $path = shift;
    my @parts = File::Spec->splitpath($path);
    return File::Spec->catfile(@parts);
}
